export const timezones = [
  // UTC
  { value: 'UTC', label: 'UTC (Coordinated Universal Time)', region: 'Universal' },
  
  // North America
  { value: 'America/New_York', label: 'Eastern Time (New York) (UTC-5/-4)', region: 'North America' },
  { value: 'America/Chicago', label: 'Central Time (Chicago) (UTC-6/-5)', region: 'North America' },
  { value: 'America/Denver', label: 'Mountain Time (Denver) (UTC-7/-6)', region: 'North America' },
  { value: 'America/Phoenix', label: 'Mountain Time (Phoenix) (UTC-7)', region: 'North America' },
  { value: 'America/Los_Angeles', label: 'Pacific Time (Los Angeles) (UTC-8/-7)', region: 'North America' },
  { value: 'America/Anchorage', label: 'Alaska Time (Anchorage) (UTC-9/-8)', region: 'North America' },
  { value: 'Pacific/Honolulu', label: 'Hawaii Time (Honolulu) (UTC-10)', region: 'North America' },
  { value: 'America/Toronto', label: 'Eastern Time (Toronto) (UTC-5/-4)', region: 'North America' },
  { value: 'America/Vancouver', label: 'Pacific Time (Vancouver) (UTC-8/-7)', region: 'North America' },
  { value: 'America/Montreal', label: 'Eastern Time (Montreal) (UTC-5/-4)', region: 'North America' },
  { value: 'America/Halifax', label: 'Atlantic Time (Halifax) (UTC-4/-3)', region: 'North America' },
  { value: 'America/St_Johns', label: 'Newfoundland Time (St. Johns) (UTC-3:30/-2:30)', region: 'North America' },
  { value: 'America/Mexico_City', label: 'Central Time (Mexico City) (UTC-6/-5)', region: 'North America' },
  { value: 'America/Tijuana', label: 'Pacific Time (Tijuana) (UTC-8/-7)', region: 'North America' },
  { value: 'America/Cancun', label: 'Eastern Time (Cancun) (UTC-5)', region: 'North America' },
  
  // South America
  { value: 'America/Sao_Paulo', label: 'Brasília Time (São Paulo) (UTC-3/-2)', region: 'South America' },
  { value: 'America/Buenos_Aires', label: 'Argentina Time (Buenos Aires) (UTC-3)', region: 'South America' },
  { value: 'America/Santiago', label: 'Chile Time (Santiago) (UTC-4/-3)', region: 'South America' },
  { value: 'America/Lima', label: 'Peru Time (Lima) (UTC-5)', region: 'South America' },
  { value: 'America/Bogota', label: 'Colombia Time (Bogotá) (UTC-5)', region: 'South America' },
  { value: 'America/Caracas', label: 'Venezuela Time (Caracas) (UTC-4)', region: 'South America' },
  { value: 'America/La_Paz', label: 'Bolivia Time (La Paz) (UTC-4)', region: 'South America' },
  { value: 'America/Asuncion', label: 'Paraguay Time (Asunción) (UTC-4/-3)', region: 'South America' },
  { value: 'America/Montevideo', label: 'Uruguay Time (Montevideo) (UTC-3/-2)', region: 'South America' },
  { value: 'America/Guyana', label: 'Guyana Time (Georgetown) (UTC-4)', region: 'South America' },
  { value: 'America/Paramaribo', label: 'Suriname Time (Paramaribo) (UTC-3)', region: 'South America' },
  { value: 'America/Cayenne', label: 'French Guiana Time (Cayenne) (UTC-3)', region: 'South America' },
  
  // Central America & Caribbean
  { value: 'America/Guatemala', label: 'Central Time (Guatemala City) (UTC-6)', region: 'Central America' },
  { value: 'America/Tegucigalpa', label: 'Central Time (Tegucigalpa) (UTC-6)', region: 'Central America' },
  { value: 'America/Managua', label: 'Central Time (Managua) (UTC-6)', region: 'Central America' },
  { value: 'America/Costa_Rica', label: 'Central Time (San José) (UTC-6)', region: 'Central America' },
  { value: 'America/Panama', label: 'Eastern Time (Panama City) (UTC-5)', region: 'Central America' },
  { value: 'America/Belize', label: 'Central Time (Belize City) (UTC-6)', region: 'Central America' },
  { value: 'America/El_Salvador', label: 'Central Time (San Salvador) (UTC-6)', region: 'Central America' },
  { value: 'America/Jamaica', label: 'Eastern Time (Kingston) (UTC-5)', region: 'Caribbean' },
  { value: 'America/Havana', label: 'Cuba Time (Havana) (UTC-5/-4)', region: 'Caribbean' },
  { value: 'America/Santo_Domingo', label: 'Atlantic Time (Santo Domingo) (UTC-4)', region: 'Caribbean' },
  { value: 'America/Port_of_Spain', label: 'Atlantic Time (Port of Spain) (UTC-4)', region: 'Caribbean' },
  { value: 'America/Barbados', label: 'Atlantic Time (Bridgetown) (UTC-4)', region: 'Caribbean' },
  { value: 'America/Nassau', label: 'Eastern Time (Nassau) (UTC-5/-4)', region: 'Caribbean' },
  
  // Europe
  { value: 'Europe/London', label: 'Greenwich Mean Time (London) (UTC+0/+1)', region: 'Europe' },
  { value: 'Europe/Dublin', label: 'Greenwich Mean Time (Dublin) (UTC+0/+1)', region: 'Europe' },
  { value: 'Europe/Lisbon', label: 'Western European Time (Lisbon) (UTC+0/+1)', region: 'Europe' },
  { value: 'Europe/Paris', label: 'Central European Time (Paris) (UTC+1/+2)', region: 'Europe' },
  { value: 'Europe/Berlin', label: 'Central European Time (Berlin) (UTC+1/+2)', region: 'Europe' },
  { value: 'Europe/Rome', label: 'Central European Time (Rome) (UTC+1/+2)', region: 'Europe' },
  { value: 'Europe/Madrid', label: 'Central European Time (Madrid) (UTC+1/+2)', region: 'Europe' },
  { value: 'Europe/Amsterdam', label: 'Central European Time (Amsterdam) (UTC+1/+2)', region: 'Europe' },
  { value: 'Europe/Brussels', label: 'Central European Time (Brussels) (UTC+1/+2)', region: 'Europe' },
  { value: 'Europe/Vienna', label: 'Central European Time (Vienna) (UTC+1/+2)', region: 'Europe' },
  { value: 'Europe/Zurich', label: 'Central European Time (Zurich) (UTC+1/+2)', region: 'Europe' },
  { value: 'Europe/Stockholm', label: 'Central European Time (Stockholm) (UTC+1/+2)', region: 'Europe' },
  { value: 'Europe/Oslo', label: 'Central European Time (Oslo) (UTC+1/+2)', region: 'Europe' },
  { value: 'Europe/Copenhagen', label: 'Central European Time (Copenhagen) (UTC+1/+2)', region: 'Europe' },
  { value: 'Europe/Helsinki', label: 'Eastern European Time (Helsinki) (UTC+2/+3)', region: 'Europe' },
  { value: 'Europe/Warsaw', label: 'Central European Time (Warsaw) (UTC+1/+2)', region: 'Europe' },
  { value: 'Europe/Prague', label: 'Central European Time (Prague) (UTC+1/+2)', region: 'Europe' },
  { value: 'Europe/Budapest', label: 'Central European Time (Budapest) (UTC+1/+2)', region: 'Europe' },
  { value: 'Europe/Bucharest', label: 'Eastern European Time (Bucharest) (UTC+2/+3)', region: 'Europe' },
  { value: 'Europe/Athens', label: 'Eastern European Time (Athens) (UTC+2/+3)', region: 'Europe' },
  { value: 'Europe/Sofia', label: 'Eastern European Time (Sofia) (UTC+2/+3)', region: 'Europe' },
  { value: 'Europe/Zagreb', label: 'Central European Time (Zagreb) (UTC+1/+2)', region: 'Europe' },
  { value: 'Europe/Belgrade', label: 'Central European Time (Belgrade) (UTC+1/+2)', region: 'Europe' },
  { value: 'Europe/Sarajevo', label: 'Central European Time (Sarajevo) (UTC+1/+2)', region: 'Europe' },
  { value: 'Europe/Ljubljana', label: 'Central European Time (Ljubljana) (UTC+1/+2)', region: 'Europe' },
  { value: 'Europe/Skopje', label: 'Central European Time (Skopje) (UTC+1/+2)', region: 'Europe' },
  { value: 'Europe/Podgorica', label: 'Central European Time (Podgorica) (UTC+1/+2)', region: 'Europe' },
  { value: 'Europe/Tallinn', label: 'Eastern European Time (Tallinn) (UTC+2/+3)', region: 'Europe' },
  { value: 'Europe/Riga', label: 'Eastern European Time (Riga) (UTC+2/+3)', region: 'Europe' },
  { value: 'Europe/Vilnius', label: 'Eastern European Time (Vilnius) (UTC+2/+3)', region: 'Europe' },
  { value: 'Europe/Moscow', label: 'Moscow Time (Moscow) (UTC+3)', region: 'Europe' },
  { value: 'Europe/Kiev', label: 'Eastern European Time (Kyiv) (UTC+2/+3)', region: 'Europe' },
  { value: 'Europe/Minsk', label: 'Moscow Time (Minsk) (UTC+3)', region: 'Europe' },
  { value: 'Europe/Chisinau', label: 'Eastern European Time (Chisinau) (UTC+2/+3)', region: 'Europe' },
  { value: 'Europe/Reykjavik', label: 'Greenwich Mean Time (Reykjavik) (UTC+0)', region: 'Europe' },
  
  // Asia
  { value: 'Asia/Dubai', label: 'Gulf Standard Time (Dubai) (UTC+4)', region: 'Middle East' },
  { value: 'Asia/Qatar', label: 'Arabia Standard Time (Doha) (UTC+3)', region: 'Middle East' },
  { value: 'Asia/Riyadh', label: 'Arabia Standard Time (Riyadh) (UTC+3)', region: 'Middle East' },
  { value: 'Asia/Kuwait', label: 'Arabia Standard Time (Kuwait City) (UTC+3)', region: 'Middle East' },
  { value: 'Asia/Bahrain', label: 'Arabia Standard Time (Manama) (UTC+3)', region: 'Middle East' },
  { value: 'Asia/Muscat', label: 'Gulf Standard Time (Muscat) (UTC+4)', region: 'Middle East' },
  { value: 'Asia/Baghdad', label: 'Arabia Standard Time (Baghdad) (UTC+3)', region: 'Middle East' },
  { value: 'Asia/Tehran', label: 'Iran Standard Time (Tehran) (UTC+3:30/+4:30)', region: 'Middle East' },
  { value: 'Asia/Jerusalem', label: 'Israel Standard Time (Jerusalem) (UTC+2/+3)', region: 'Middle East' },
  { value: 'Asia/Damascus', label: 'Eastern European Time (Damascus) (UTC+2/+3)', region: 'Middle East' },
  { value: 'Asia/Amman', label: 'Eastern European Time (Amman) (UTC+2/+3)', region: 'Middle East' },
  { value: 'Asia/Beirut', label: 'Eastern European Time (Beirut) (UTC+2/+3)', region: 'Middle East' },
  { value: 'Europe/Istanbul', label: 'Turkey Time (Istanbul) (UTC+3)', region: 'Middle East' },
  
  { value: 'Asia/Karachi', label: 'Pakistan Standard Time (Karachi) (UTC+5)', region: 'Asia' },
  { value: 'Asia/Islamabad', label: 'Pakistan Standard Time (Islamabad) (UTC+5)', region: 'Asia' },
  { value: 'Asia/Mumbai', label: 'India Standard Time (Mumbai) (UTC+5:30)', region: 'Asia' },
  { value: 'Asia/Kolkata', label: 'India Standard Time (Kolkata) (UTC+5:30)', region: 'Asia' },
  { value: 'Asia/Delhi', label: 'India Standard Time (New Delhi) (UTC+5:30)', region: 'Asia' },
  { value: 'Asia/Dhaka', label: 'Bangladesh Standard Time (Dhaka) (UTC+6)', region: 'Asia' },
  { value: 'Asia/Colombo', label: 'Sri Lanka Standard Time (Colombo) (UTC+5:30)', region: 'Asia' },
  { value: 'Asia/Kathmandu', label: 'Nepal Time (Kathmandu) (UTC+5:45)', region: 'Asia' },
  { value: 'Asia/Thimphu', label: 'Bhutan Time (Thimphu) (UTC+6)', region: 'Asia' },
  { value: 'Asia/Kabul', label: 'Afghanistan Time (Kabul) (UTC+4:30)', region: 'Asia' },
  { value: 'Asia/Tashkent', label: 'Uzbekistan Time (Tashkent) (UTC+5)', region: 'Asia' },
  { value: 'Asia/Almaty', label: 'Almaty Time (Almaty) (UTC+6)', region: 'Asia' },
  { value: 'Asia/Bishkek', label: 'Kyrgyzstan Time (Bishkek) (UTC+6)', region: 'Asia' },
  { value: 'Asia/Dushanbe', label: 'Tajikistan Time (Dushanbe) (UTC+5)', region: 'Asia' },
  { value: 'Asia/Ashgabat', label: 'Turkmenistan Time (Ashgabat) (UTC+5)', region: 'Asia' },
  
  { value: 'Asia/Shanghai', label: 'China Standard Time (Shanghai) (UTC+8)', region: 'Asia' },
  { value: 'Asia/Beijing', label: 'China Standard Time (Beijing) (UTC+8)', region: 'Asia' },
  { value: 'Asia/Hong_Kong', label: 'Hong Kong Time (Hong Kong) (UTC+8)', region: 'Asia' },
  { value: 'Asia/Macau', label: 'China Standard Time (Macau) (UTC+8)', region: 'Asia' },
  { value: 'Asia/Taipei', label: 'China Standard Time (Taipei) (UTC+8)', region: 'Asia' },
  { value: 'Asia/Singapore', label: 'Singapore Standard Time (Singapore) (UTC+8)', region: 'Asia' },
  { value: 'Asia/Kuala_Lumpur', label: 'Malaysia Time (Kuala Lumpur) (UTC+8)', region: 'Asia' },
  { value: 'Asia/Bangkok', label: 'Indochina Time (Bangkok) (UTC+7)', region: 'Asia' },
  { value: 'Asia/Ho_Chi_Minh', label: 'Indochina Time (Ho Chi Minh City) (UTC+7)', region: 'Asia' },
  { value: 'Asia/Phnom_Penh', label: 'Indochina Time (Phnom Penh) (UTC+7)', region: 'Asia' },
  { value: 'Asia/Vientiane', label: 'Indochina Time (Vientiane) (UTC+7)', region: 'Asia' },
  { value: 'Asia/Jakarta', label: 'Western Indonesia Time (Jakarta) (UTC+7)', region: 'Asia' },
  { value: 'Asia/Makassar', label: 'Central Indonesia Time (Makassar) (UTC+8)', region: 'Asia' },
  { value: 'Asia/Jayapura', label: 'Eastern Indonesia Time (Jayapura) (UTC+9)', region: 'Asia' },
  { value: 'Asia/Manila', label: 'Philippine Standard Time (Manila) (UTC+8)', region: 'Asia' },
  { value: 'Asia/Brunei', label: 'Brunei Darussalam Time (Bandar Seri Begawan) (UTC+8)', region: 'Asia' },
  { value: 'Asia/Dili', label: 'Timor-Leste Time (Dili) (UTC+9)', region: 'Asia' },
  { value: 'Asia/Yangon', label: 'Myanmar Time (Yangon) (UTC+6:30)', region: 'Asia' },
  
  { value: 'Asia/Tokyo', label: 'Japan Standard Time (Tokyo) (UTC+9)', region: 'Asia' },
  { value: 'Asia/Seoul', label: 'Korea Standard Time (Seoul) (UTC+9)', region: 'Asia' },
  { value: 'Asia/Pyongyang', label: 'Pyongyang Time (Pyongyang) (UTC+9)', region: 'Asia' },
  { value: 'Asia/Ulaanbaatar', label: 'Ulaanbaatar Time (Ulaanbaatar) (UTC+8)', region: 'Asia' },
  
  { value: 'Asia/Yekaterinburg', label: 'Yekaterinburg Time (Yekaterinburg) (UTC+5)', region: 'Asia' },
  { value: 'Asia/Omsk', label: 'Omsk Time (Omsk) (UTC+6)', region: 'Asia' },
  { value: 'Asia/Krasnoyarsk', label: 'Krasnoyarsk Time (Krasnoyarsk) (UTC+7)', region: 'Asia' },
  { value: 'Asia/Irkutsk', label: 'Irkutsk Time (Irkutsk) (UTC+8)', region: 'Asia' },
  { value: 'Asia/Yakutsk', label: 'Yakutsk Time (Yakutsk) (UTC+9)', region: 'Asia' },
  { value: 'Asia/Vladivostok', label: 'Vladivostok Time (Vladivostok) (UTC+10)', region: 'Asia' },
  { value: 'Asia/Magadan', label: 'Magadan Time (Magadan) (UTC+11)', region: 'Asia' },
  { value: 'Asia/Kamchatka', label: 'Kamchatka Time (Petropavlovsk-Kamchatsky) (UTC+12)', region: 'Asia' },
  
  // Africa
  { value: 'Africa/Cairo', label: 'Eastern European Time (Cairo) (UTC+2)', region: 'Africa' },
  { value: 'Africa/Lagos', label: 'West Africa Time (Lagos) (UTC+1)', region: 'Africa' },
  { value: 'Africa/Johannesburg', label: 'South Africa Standard Time (Johannesburg) (UTC+2)', region: 'Africa' },
  { value: 'Africa/Nairobi', label: 'East Africa Time (Nairobi) (UTC+3)', region: 'Africa' },
  { value: 'Africa/Addis_Ababa', label: 'East Africa Time (Addis Ababa) (UTC+3)', region: 'Africa' },
  { value: 'Africa/Casablanca', label: 'Western European Time (Casablanca) (UTC+0/+1)', region: 'Africa' },
  { value: 'Africa/Algiers', label: 'Central European Time (Algiers) (UTC+1)', region: 'Africa' },
  { value: 'Africa/Tunis', label: 'Central European Time (Tunis) (UTC+1)', region: 'Africa' },
  { value: 'Africa/Tripoli', label: 'Eastern European Time (Tripoli) (UTC+2)', region: 'Africa' },
  { value: 'Africa/Khartoum', label: 'Central Africa Time (Khartoum) (UTC+2)', region: 'Africa' },
  { value: 'Africa/Kampala', label: 'East Africa Time (Kampala) (UTC+3)', region: 'Africa' },
  { value: 'Africa/Dar_es_Salaam', label: 'East Africa Time (Dar es Salaam) (UTC+3)', region: 'Africa' },
  { value: 'Africa/Kigali', label: 'Central Africa Time (Kigali) (UTC+2)', region: 'Africa' },
  { value: 'Africa/Lusaka', label: 'Central Africa Time (Lusaka) (UTC+2)', region: 'Africa' },
  { value: 'Africa/Harare', label: 'Central Africa Time (Harare) (UTC+2)', region: 'Africa' },
  { value: 'Africa/Maputo', label: 'Central Africa Time (Maputo) (UTC+2)', region: 'Africa' },
  { value: 'Africa/Gaborone', label: 'Central Africa Time (Gaborone) (UTC+2)', region: 'Africa' },
  { value: 'Africa/Windhoek', label: 'Central Africa Time (Windhoek) (UTC+2)', region: 'Africa' },
  { value: 'Africa/Kinshasa', label: 'West Africa Time (Kinshasa) (UTC+1)', region: 'Africa' },
  { value: 'Africa/Brazzaville', label: 'West Africa Time (Brazzaville) (UTC+1)', region: 'Africa' },
  { value: 'Africa/Accra', label: 'Greenwich Mean Time (Accra) (UTC+0)', region: 'Africa' },
  { value: 'Africa/Abidjan', label: 'Greenwich Mean Time (Abidjan) (UTC+0)', region: 'Africa' },
  { value: 'Africa/Dakar', label: 'Greenwich Mean Time (Dakar) (UTC+0)', region: 'Africa' },
  { value: 'Africa/Bamako', label: 'Greenwich Mean Time (Bamako) (UTC+0)', region: 'Africa' },
  { value: 'Africa/Conakry', label: 'Greenwich Mean Time (Conakry) (UTC+0)', region: 'Africa' },
  { value: 'Africa/Monrovia', label: 'Greenwich Mean Time (Monrovia) (UTC+0)', region: 'Africa' },
  
  // Oceania
  { value: 'Australia/Sydney', label: 'Australian Eastern Time (Sydney) (UTC+10/+11)', region: 'Oceania' },
  { value: 'Australia/Melbourne', label: 'Australian Eastern Time (Melbourne) (UTC+10/+11)', region: 'Oceania' },
  { value: 'Australia/Brisbane', label: 'Australian Eastern Time (Brisbane) (UTC+10)', region: 'Oceania' },
  { value: 'Australia/Perth', label: 'Australian Western Time (Perth) (UTC+8)', region: 'Oceania' },
  { value: 'Australia/Adelaide', label: 'Australian Central Time (Adelaide) (UTC+9:30/+10:30)', region: 'Oceania' },
  { value: 'Australia/Darwin', label: 'Australian Central Time (Darwin) (UTC+9:30)', region: 'Oceania' },
  { value: 'Australia/Hobart', label: 'Australian Eastern Time (Hobart) (UTC+10/+11)', region: 'Oceania' },
  { value: 'Australia/Canberra', label: 'Australian Eastern Time (Canberra) (UTC+10/+11)', region: 'Oceania' },
  { value: 'Pacific/Auckland', label: 'New Zealand Standard Time (Auckland) (UTC+12/+13)', region: 'Oceania' },
  { value: 'Pacific/Wellington', label: 'New Zealand Standard Time (Wellington) (UTC+12/+13)', region: 'Oceania' },
  { value: 'Pacific/Chatham', label: 'Chatham Standard Time (Chatham Islands) (UTC+12:45/+13:45)', region: 'Oceania' },
  { value: 'Pacific/Fiji', label: 'Fiji Time (Suva) (UTC+12/+13)', region: 'Oceania' },
  { value: 'Pacific/Tongatapu', label: 'Tonga Time (Nuku\'alofa) (UTC+13)', region: 'Oceania' },
  { value: 'Pacific/Apia', label: 'Samoa Standard Time (Apia) (UTC+13/+14)', region: 'Oceania' },
  { value: 'Pacific/Tahiti', label: 'Tahiti Time (Papeete) (UTC-10)', region: 'Oceania' },
  { value: 'Pacific/Marquesas', label: 'Marquesas Time (Taiohae) (UTC-9:30)', region: 'Oceania' },
  { value: 'Pacific/Gambier', label: 'Gambier Time (Rikitea) (UTC-9)', region: 'Oceania' },
  { value: 'Pacific/Noumea', label: 'New Caledonia Time (Nouméa) (UTC+11)', region: 'Oceania' },
  { value: 'Pacific/Port_Moresby', label: 'Papua New Guinea Time (Port Moresby) (UTC+10)', region: 'Oceania' },
  { value: 'Pacific/Guadalcanal', label: 'Solomon Islands Time (Honiara) (UTC+11)', region: 'Oceania' },
  { value: 'Pacific/Efate', label: 'Vanuatu Time (Port Vila) (UTC+11)', region: 'Oceania' },
  { value: 'Pacific/Norfolk', label: 'Norfolk Island Time (Kingston) (UTC+11/+12)', region: 'Oceania' },
  { value: 'Pacific/Palau', label: 'Palau Time (Ngerulmud) (UTC+9)', region: 'Oceania' },
  { value: 'Pacific/Guam', label: 'Chamorro Standard Time (Hagåtña) (UTC+10)', region: 'Oceania' },
  { value: 'Pacific/Saipan', label: 'Chamorro Standard Time (Saipan) (UTC+10)', region: 'Oceania' },
  { value: 'Pacific/Chuuk', label: 'Chuuk Time (Weno) (UTC+10)', region: 'Oceania' },
  { value: 'Pacific/Pohnpei', label: 'Pohnpei Time (Palikir) (UTC+11)', region: 'Oceania' },
  { value: 'Pacific/Kosrae', label: 'Kosrae Time (Tofol) (UTC+11)', region: 'Oceania' },
  { value: 'Pacific/Majuro', label: 'Marshall Islands Time (Majuro) (UTC+12)', region: 'Oceania' },
  { value: 'Pacific/Nauru', label: 'Nauru Time (Yaren) (UTC+12)', region: 'Oceania' },
  { value: 'Pacific/Tarawa', label: 'Gilbert Island Time (South Tarawa) (UTC+12)', region: 'Oceania' },
  { value: 'Pacific/Enderbury', label: 'Phoenix Island Time (Enderbury) (UTC+13)', region: 'Oceania' },
  { value: 'Pacific/Kiritimati', label: 'Line Islands Time (Kiritimati) (UTC+14)', region: 'Oceania' },
  
  // Atlantic Ocean
  { value: 'Atlantic/Azores', label: 'Azores Time (Ponta Delgada) (UTC-1/+0)', region: 'Atlantic' },
  { value: 'Atlantic/Madeira', label: 'Western European Time (Funchal) (UTC+0/+1)', region: 'Atlantic' },
  { value: 'Atlantic/Canary', label: 'Western European Time (Las Palmas) (UTC+0/+1)', region: 'Atlantic' },
  { value: 'Atlantic/Cape_Verde', label: 'Cape Verde Time (Praia) (UTC-1)', region: 'Atlantic' },
  { value: 'Atlantic/Reykjavik', label: 'Greenwich Mean Time (Reykjavik) (UTC+0)', region: 'Atlantic' },
  { value: 'Atlantic/Faroe', label: 'Western European Time (Tórshavn) (UTC+0/+1)', region: 'Atlantic' },
  { value: 'Atlantic/South_Georgia', label: 'South Georgia Time (King Edward Point) (UTC-2)', region: 'Atlantic' },
  { value: 'Atlantic/Stanley', label: 'Falkland Islands Time (Stanley) (UTC-3)', region: 'Atlantic' },
  { value: 'Atlantic/St_Helena', label: 'Greenwich Mean Time (Jamestown) (UTC+0)', region: 'Atlantic' },
  
  // Indian Ocean
  { value: 'Indian/Mauritius', label: 'Mauritius Time (Port Louis) (UTC+4)', region: 'Indian Ocean' },
  { value: 'Indian/Reunion', label: 'Réunion Time (Saint-Denis) (UTC+4)', region: 'Indian Ocean' },
  { value: 'Indian/Mayotte', label: 'East Africa Time (Mamoudzou) (UTC+3)', region: 'Indian Ocean' },
  { value: 'Indian/Comoro', label: 'East Africa Time (Moroni) (UTC+3)', region: 'Indian Ocean' },
  { value: 'Indian/Antananarivo', label: 'East Africa Time (Antananarivo) (UTC+3)', region: 'Indian Ocean' },
  { value: 'Indian/Maldives', label: 'Maldives Time (Malé) (UTC+5)', region: 'Indian Ocean' },
  { value: 'Indian/Chagos', label: 'Indian Ocean Time (Diego Garcia) (UTC+6)', region: 'Indian Ocean' },
  { value: 'Indian/Cocos', label: 'Cocos Islands Time (West Island) (UTC+6:30)', region: 'Indian Ocean' },
  { value: 'Indian/Christmas', label: 'Christmas Island Time (Flying Fish Cove) (UTC+7)', region: 'Indian Ocean' },
  { value: 'Indian/Kerguelen', label: 'French Southern & Antarctic Time (Port-aux-Français) (UTC+5)', region: 'Indian Ocean' }
];