name: vibe-flow-pos
services:
- name: web
  source_dir: /
  github:
    repo: loanspur/vibe-flow-point-of-sale
    branch: dev_branch
  run_command: nginx -g 'daemon off;'
  build_command: |
    npm cache clean --force
    rm -rf node_modules package-lock.json
    npm install --legacy-peer-deps --no-optional --production=false
    npm run build:prod
  dockerfile_path: Dockerfile
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xxs
  environment_slug: node-js
  envs:
  - key: NODE_ENV
    value: production
  - key: VITE_SUPABASE_URL
    value: ${VITE_SUPABASE_URL}
  - key: VITE_SUPABASE_ANON_KEY
    value: ${VITE_SUPABASE_ANON_KEY}
  - key: VITE_DEV_MODE
    value: "false"
  - key: VITE_API_URL
    value: ${VITE_API_URL}